version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bluetags
    overwrite: yes

permissions:
  - object: /home/ubuntu/bluetags
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
   BeforeInstall:
    - location: scripts/before-deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: ubuntu
