version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bluetags
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ubuntu
